apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend
spec:
  type: ClusterIP   # Internal only
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000        # Service port
      targetPort: 5000  # Container port

