# config.yml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  # Control plane node
  - role: control-plane
    image: kindest/node:v1.28.0
    extraPortMappings:
      - containerPort: 80      # HTTP
        hostPort: 80
        protocol: TCP
      - containerPort: 443     # HTTPS
        hostPort: 443
        protocol: TCP
      - containerPort: 30007   # Node.js NodePort
        hostPort: 30007
        protocol: TCP
    extraMounts:
      - hostPath: /mnt/kind-storage/mongo
        containerPath: /data/mongo

  # Worker node 1
  - role: worker
    image: kindest/node:v1.28.0
    extraMounts:
      - hostPath: /mnt/kind-storage/mongo
        containerPath: /data/mongo

  # Worker node 2
  - role: worker
    image: kindest/node:v1.28.0
    extraMounts:
      - hostPath: /mnt/kind-storage/mongo
        containerPath: /data/mongo

