# Headless Service for MongoDB StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: database
spec:
  clusterIP: None       # Headless service for stable DNS
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

