apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: frontend-vpa
  namespace: frontend
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: frontend-deployment
  updatePolicy:
    updateMode: "off"   # can also be "Initial" or "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: frontend
      minAllowed:
        cpu: "200m"
        memory: "256Mi"
      maxAllowed:
        cpu: "1"
        memory: "1Gi"

